article:
  aargauerzeitung: lastdot
  aerzteblatt: previous
  aerztezeitung: last
  admin: last
  ardmediathek: pprevious
  bag: last
  berliner-zeitung: lastdot
  bernerzeitung: last
  br: lastcomma
  comm4u: page
  dailymail: previous
  deutschlandfunk: page
  derstandard: previous
  dieostschweiz: last
  epochtimes: last
  focus: last_
  fm1today: last
  fr: last
  gov-in: page
  heise: last
  meinbezirk: last_
  nordkurier: last
  linth24: first
  nachdenkseiten: page
  nau: last
  ndr: lastcomma
  n-tv: last
  nzz: lastdot
  pharmazeutische-zeitung: last
  parlament: page
  rnd: last
  rt: first
  snanews: last
  stgallen24: first
  tagesanzeiger: last
  tagblatt: lastdot
  t-online: previous
  tips: first
  unilu: last
  unzensuriert: first
  welt: previous
sitename:
  2020news: 2020 News
  achgut: Achgut.com
  admin: Bundesrat
  aerztezeitung: AerzteZeitung
  ardmediathek: ARD
  bag: BAG
  baernerbaer: Bärnerbär
  berthub: berthub
  gatesfoundation: Bill & Melinda Gates Foundation 
  deutsche-apotheker-zeitung: Deutsche Apotheker Zeitung
  derstandard: Der Standard
  dieostschweiz: Die Ostschweiz
  dgpi: Deutsche Gesellschaft für Pädiatrische Infektiologie
  epochtimes: Epoch Times
  fm1today: FM1 Today
  focus: Focus Online
  fr: Frankfurter Rundschau
  gesundheitstipp: Gesundheitstipp
  gov-in: Government of India
  heise: Telepolis
  infosperber: INFOsperber
  insideparadeplatz: In$ide Paradeplatz
  kenfm: kenFM
  kinder-maskenpetition: Kinder-Maskenpetition
  ktipp: Ktipp
  medinside: medinside.ch
  multipolar-magazin: multipolar
  nachdenkseiten: NachDenkSeiten
  nordkurier: Nordkurier
  ndr: NDR
  n-tv: ntv
  nzz: NZZ
  nytimes: The New York Times
  parlament: Das Schweizer Parlament
  pharmazeutische-zeitung: Pharmazeutische Zeitung
  reitschuster: reitschuster
  rnd: RND
  rubikon: Rubikon
  srf: SRF
  substack: substack.com
  suedostschweiz: südostschweiz
  swissmedic: Swissmedic
  swr: SWR
  tagesanzeiger: Tagesanzeiger
  tagblatt: tagblatt.ch
  tkp: tp - Science & Technology
  uncutnews: Uncut-News
  unser-mitteleuropa: Unser Mitteleuropa
  welt: Die Welt
  weltwoche: Weltwoche
  zdf: ZDF
  zeitpunkt: ZE!TPUNKT
  zueriost: züriost
tag:
  1bis19: 1bis19
  admin: bundesrat
  bag: bundesrat
  bernerzeitung: bernerzeitung
  cducsu: cducsu
  deutsche-apotheker-zeitung: daz
  dgkj: dgkj
  dgpi: dgpi
  ema: ema
  fm1today: fm1today
  infekt: infekt
  meinbezirk: meinbezirk
  nature: nature
  orf: orf
  parlament: parlament
  derstandard: standard
  schweizermonat: schweizermonat
  svp: svp
  t-online: t-online
  zeitpunkt: zeitpunkt
subtitle:
  2020news: last-
  aerzteblatt: h1
  corona-transition: last
  globalresearch: last-
  harald-walach: last-
  Handelsblatt: ignore
  insideparadeplatz: last-
  infekt: last-
  infosperber: last-
  journalistenwatch: last›
  kenfm: last
  medinside.ch: ignore
  mdr: last
  nordkurier: last
  nzz: last
  The New York Times: ignore
  pharmazeutische-zeitung: last
  peds-ansichten: last
  pubmed: last-
  reitschuster: last-
  schweizermonat: last–
  svp: last-
  tagblatt: last
  tkp: last-
  uncutnews: last
  Unser Mitteleuropa: ignore
  unzensuriert: last-
  verfassungsfreunde: last
  welt: last-
  weltwoche-daily: last-
  zeitpunkt: h2
uri:
  www.dailymail.co.uk: second
  pib.gov.in: secondtolast
  fassadenkratzer.wordpress.com: first
  www.bag.admin.ch: second
  pubmed.ncbi.nlm.nih.gov: first
  www.ema.europa.eu: second
  www.i-med.ac.at: second
cleanurl:
  nachdenkseiten: false
  deutschlandfunk: false
country:
  achgut: DE
  corona-blog: DE
  corona-transition: CH
  fassadenkratzer: DE
  globalresearch: World
  journalistenwatch: DE
  report24: AT
  rt: DE
  rubikon: DE
  sciencefiles: DE
  telegra: EU
  unser-mitteleuropa: EU
filename:
  rnd: ignoredowncase
  dieostschweiz: ignoredowncase
  kinder-maskenpetition: ignoredowncase
category:
  n-tv: MSM
  tagesanzeiger: MSM
  welt: MSM
  focus: MSM
  nzz: MSM
description:
  achgut: last/
content:
  rubikon: md
