article:
  aerzteblatt: previous
  aerztezeitung: last
  admin: last
  ardmediathek: pprevious
  berliner-zeitung: lastdot
  deutschlandfunk: page
  dieostschweiz: last
  epochtimes: last
  focus: last_
  fm1today: last
  heise: last
  meinbezirk: last_
  nordkurier: last
  linth24: first
  nachdenkseiten: page
  nau: last
  ndr: lastcomma
  n-tv: last
  nzz: lastdot
  pharmazeutische-zeitung: last
  rnd: last
  rt: first
  tagesanzeiger: last
  tagblatt: lastdot
  welt: previous
sitename:
  2020news: 2020 News
  achgut: Achgut.com
  admin: Bundesrat
  aerztezeitung: AerzteZeitung
  ardmediathek: ARD
  deutsche-apotheker-zeitung: Deutsche Apotheker Zeitung
  dieostschweiz: Die Ostschweiz
  epochtimes: Epoch Times
  fm1today: FM1 Today
  focus: Focus Online
  heise: Telepolis
  infosperber: INFOsperber
  insideparadeplatz: In$ide Paradeplatz
  kenfm: kenFM
  kinder-maskenpetition: Kinder-Maskenpetition
  ktipp: Ktipp
  medinside: medinside.ch
  multipolar-magazin: multipolar
  nachdenkseiten: NachDenkSeiten
  nordkurier: Nordkurier
  ndr: NDR
  n-tv: ntv
  nzz: NZZ
  pharmazeutische-zeitung: Pharmazeutische Zeitung
  reitschuster: reitschuster
  rnd: RND
  rubikon: Rubikon
  srf: SRF
  substack: substack.com
  swissmedic: Swissmedic
  swr: SWR
  tagesanzeiger: Tagesanzeiger
  tagblatt: tagblatt.ch
  tkp: tp - Science & Technology
  uncutnews: Uncut-News
  unser-mitteleuropa: Unser Mitteleuropa
  welt: Die Welt
  weltwoche: Weltwoche
  zdf: ZDF
  zeitpunkt: ZE!TPUNKT
  zueriost: züriost
tag:
  2020news: 2020news
  aargau-zuerich: aargau-zuerich
  achgut: achgut
  aerzteblatt: ärzteblatt
  corona-blog: corona-blog
  deutsche-apotheker-zeitung: daz
  dgkj: dgkj
  fm1today: fm1today
  focus: focus
  insideparadeplatz: inside-paradeplatz
  medinside: medinside
  meinbezirk: meinbezirk
  rt: rt
  substack: substack
  tagblatt: tagblatt
  tichyseinblick: tichyseinblick
  tkp: tkp
  vera-lengsfeld: vera-lengsfeld
  welt: welt
  zeitpunkt: zeitpunkt
subtitle:
  2020news: last
  corona-blog: last
  corona-transition: last
  insideparadeplatz: last
  infekt: last
  infosperber: last
  kenfm: last
  medinside: ignore-og
  nordkurier: last
  pharmazeutische-zeitung: last
  reitschuster: last-
  tagblatt: last
  uncutnews: last
  unser-mitteleuropa: ignore-og
  welt: last
  verfassungsfreunde: last
  weltwoche-daily: last
cleanurl:
  nachdenkseiten: false
  deutschlandfunk: false
country:
  achgut: DE
  corona-transition: CH
  rt: DE
  rubikon: DE
  sciencefiles: DE
